[package]
name = "autoclimb-lang-generic"
version.workspace = true
edition.workspace = true

[dependencies]
autoclimb-types.workspace = true
autoclimb-detectors.workspace = true
autoclimb-discovery.workspace = true
autoclimb-graph.workspace = true
autoclimb-treesitter.workspace = true
serde.workspace = true
serde_json.workspace = true
regex.workspace = true

[dev-dependencies]
tempfile.workspace = true
